<?php
/**
 * File: awe_blank_object.module
 * Author: MegaDrupal
 * Website: http://megadrupal.com/
 */

/**
 * implements hook_awecontent_objects_info()
 * to declare info list objetcs what this module provide
 */
function awe_info_object_awecontent_objects_info() {
	$info = array();
	$module_path = drupal_get_path('module', 'awe_info_object');

	$info['info'] = array(
	    'js' => array(
	      $module_path . '/awecontent-info-item.js' => array('weight' => 999)
	    ),
	    'theme_callback' => 'awe_info',
	);

	return $info;
}

/**
 * Implements hook_theme().
 */
function awe_info_object_theme() {
	$themes['awe_info'] = array(
	    'path' => drupal_get_path('module', 'awe_info_object'),
	    'template' => 'awe-info',
	    'file' => 'theme.inc',
	    'variables' => array(
	      'settings' => NULL,
	      'class_random' => NULL,
	      'node' => NULL
	    ),
	);

	return $themes;
}


/**
 * Implement hook_preprocess_page()
 */
function awe_info_object_preprocess_page(&$vars) {
  	$path = drupal_get_path('module', 'awe_info_object');
  	drupal_add_css($path . '/awecontent-info-item.css');
}